### ISSUE TITLE
Missing ILSPY Folder Content

### ISSUE THREAD

**Issue by protegesolutions** [obfuscar/obfuscar#145] opened 2018-07-07 23:23 UTC
Out of the box, source 2.2.12 doesn't compile most probably because the _ilspy_ folder is empty. I can't find any doco about this. I can't restore any packages (not supported OOB).

Can someone point me to whatever it is that I'm missing? Better still, make the source complete so that ti compiles OOB.

**Comment by lextm** [comment] 2018-07-08 02:38
Duplicate of #69

**Closed by lextm** 2018-07-08 02:38 UTC
