### ISSUE TITLE
Calling System.Type.GetType() throws OutOfMemoryException

### ISSUE THREAD

**Issue by flenzneribg** [obfuscar/obfuscar#82] opened 2016-07-13 08:21 UTC
A call to `System.Type.GetType(string, bool, bool)` throws an `OutOfMemoryException` if the requested type is defined in an obfuscated assembly, and the third parameter (`ignoreCase`) is `true`.
This happens even if the class name is actually not obfuscated, i.e., `KeepPublicApi` is `true`, and `HidePrivateApi` is `false`.

The described behaviour was observed with Obfuscar 2.0 and 2.2.0, but _not with 2.0.2_.

The behaviour can be reproduced as follows:

Build an assembly from:

``` cs
using System;

namespace ObfuscarAndReflection
{
    class Program
    {
        static void Main(string[] args)
        {
            check(typeof(Klaas), false);
            Console.WriteLine();
            check(typeof(Klaas), true);

            Console.ReadKey();
        }

        private static void check(Type dipe, bool ignoreCase)
        {
            string fullTypeName = dipe.AssemblyQualifiedName;
            Console.WriteLine("Loading " + fullTypeName + " with ignoreCase set to " + ignoreCase);

            try
            {
                var type = Type.GetType(fullTypeName, true, ignoreCase);
                Console.WriteLine("Successfully loaded " + type.FullName);

                var objegged = Activator.CreateInstance(type);
                Console.WriteLine("Created an instance of " + type.FullName);
            }
            catch (OutOfMemoryException e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
            }
        }
    }

    class Klaas
    {
        private int i;

        public Klaas()
        {
            i = 0;
        }
    }
}
```

Obfuscate the assembly with the following settings:

``` xml
<?xml version='1.0'?>
<Obfuscator>
    <Var name="InPath" value="ObfuscarAndReflection\bin\Debug" />
    <Var name="OutPath" value="ObfuscarAndReflection\bin\Obfuscated" />

    <Var name="KeepPublicApi" value="true" />
    <Var name="HidePrivateApi" value="false" /> 

    <Module file="$(InPath)\ObfuscarAndReflection.exe">
    </Module>

</Obfuscator>
```

When run, the obfuscated assembly prints:

```
Loading ObfuscarAndReflection.Klaas, ObfuscarAndReflection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null with ignoreCase set to False
Successfully loaded ObfuscarAndReflection.Klaas
Created an instance of ObfuscarAndReflection.Klaas

Loading ObfuscarAndReflection.Klaas, ObfuscarAndReflection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null with ignoreCase set to True
Eine Ausnahme vom Typ "System.OutOfMemoryException" wurde ausgelöst.
   bei System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   bei System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   bei System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   bei ObfuscarAndReflection.Program.check(Type dipe, Boolean ignoreCase)
```

when using Obfuscar 2.0, 2.2.0. It works fine (no exception) with 2.0.2.

**Comment by lextm** [comment] 2016-07-16 10:42
Thanks for this detailed report.

Some investigation indicates that by disabling string obfuscation via 
```
<Var name="HideStrings" value="false" />
```
this issue can be remedied.

Thus, it is very likely to be caused by the way we wave the obfuscated strings into the assembly. I will do more analysis once I have enough time.

**Comment by SarraffPrakash** [comment] 2019-04-19 05:40
I was facing the same issue and it got fixed with the suggested setting. Thanks @lextm !

**Closed** 2020-11-28 04:48 UTC
Labels: bug, in progress
