### ISSUE TITLE
Obfuscar not working in Build Server

### ISSUE THREAD

**Issue by pavandeekshitha** [obfuscar/obfuscar#204] opened 2019-05-08 14:36 UTC
Hi Team,

I am using obfuscar for netstandard libraries. This works fine in my dev environment(VS2017 Installed) ,but when in run in my Build Server , it is not working ,I am getting the below error
I installed dotnet core 2.2 sdk in build server.
Please suggest
Failed to resolve assembly: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

Thanks
Pavan

**Comment by lextm** [comment] 2019-05-08 23:43
Duplicate of #119 . You need to make sure that the search paths are correct on both your dev environment and on the build server.

**Closed** 2019-05-08 23:43 UTC
Labels: duplicate

**Comment by pavandeekshitha** [comment] 2019-05-09 07:05
Hi Team,

Thanks for your quick response . This fixed my issue. You saved my day.
Actually in Windows desktop i did not specify the Dot Net Standard Path and it worked.
But in Build Server(Windows Server 2016),I had to explictly mention the path.
Anyway thanks

Thanks
Pavan
