### ISSUE TITLE
Error obfuscating dotnet core 2.2 webapi project

### ISSUE THREAD

**Issue by neumartin** [obfuscar/obfuscar#194] opened 2019-04-07 04:12 UTC
Im using Obfuscar in Ubuntu Linux, and when I try do obfuscate I recive this error:

Unable to resolve dependency:  Microsoft.AspNetCore.Mvc.ViewFeatures

I tried this configuration XML:

```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="/home/martin/Temp/TotemControlServicePub" />
  <Var name="OutPath" value="./Obfuscator_Output" />
  <Var name="LogFile" value="/home/martin/Temp/TotemControlServicePub" />

  <Module file="$(InPath)/Sevnt.TotemControlService.dll">
	<SkipType name="Microsoft.AspNetCore.Mvc.ViewFeatures" skipMethods="true" skipFields="true" />
  </Module>
</Obfuscator> 
```

**Comment by lextm** [comment] 2019-04-07 05:07
Duplicate of #132

**Closed** 2019-04-07 17:30 UTC
Labels: duplicate
