### ISSUE TITLE
BadImageFormatException with .net core 3.0

### ISSUE THREAD

**Issue by ErikApption** [obfuscar/obfuscar#244] opened 2019-10-24 16:35 UTC
Been trying to configure obfuscar on a .net core 3 exe and DLL, and it looks like since 3.0.100 obfuscar is broken. Is this a matter of updating Cecil?

``
Loading project obfuscar.xml...Processing assembly: MLRecognizers, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null
2>
2>Unhandled Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
2>   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics)
2>   at Mono.Cecil.PE.ImageReader.ReadImage()
2>   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
2>   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
2>   at Obfuscar.AssemblyInfo.LoadAssembly(String filename)
2>   at Obfuscar.AssemblyInfo.FromXml(Project project, XElement reader, Variables vars)
2>   at Obfuscar.Project.FromXmlReadNode(XElement reader, Project project)
2>   at Obfuscar.Project.FromXml(XDocument reader, String projectFileDirectory)
2>   at Obfuscar.Obfuscator.LoadFromReader(XDocument reader, String projectFileDirectory)
2>   at Obfuscar.Obfuscator..ctor(String projfile)
2>   at Obfuscar.Program.Main(String[] args)
``

**Comment by lextm** [comment] 2019-10-24 18:18
Just published 2.2.25 release with latest Mono Cecil. You might try it out and see if this issue is resolved.

**Comment by ErikApption** [comment] 2019-10-24 18:28
that was fast. But sadly, issue is not resolved... same error message.

**Comment by lextm** [comment] 2019-10-24 18:32
If you can use some simple C# to reproduce the crash by calling `Mono.Cecil.ModuleDefinition.ReadModule` then you can open an issue to https://github.com/jbevain/cecil/issues

As this is an upstream issue, I have no plan to work on it further.

**Comment by elitonlunardi** [comment] 2020-02-19 20:01
Hello. I'm having problems to obfuscate a code in a .net core 3.1.101 SDK version.
The current version of Obfuscar are working in this sdk version?

`Unhandled Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics)
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Obfuscar.AssemblyInfo.LoadAssembly(String filename)
   at Obfuscar.AssemblyInfo.FromXml(Project project, XElement reader, Variables vars)
   at Obfuscar.Project.FromXmlReadNode(XElement reader, Project project)
   at Obfuscar.Project.FromXml(XDocument reader, String projectFileDirectory)
   at Obfuscar.Obfuscator.LoadFromReader(XDocument reader, String projectFileDirectory)
   at Obfuscar.Obfuscator..ctor(String projfile)
   at Obfuscar.Program.Main(String[] args)`

**Comment by bessorion** [comment] 2020-03-18 11:38
New minor release for Cecil https://github.com/jbevain/cecil/releases 
Do you plan release new version with updated dependency?

**Comment by lextm** [comment] 2020-03-18 13:36
Possible duplicate of #264

**Closed by lextm** 2020-03-18 13:36 UTC
Labels: external
